"""

Add assessment_display_name to CourseGradingAssignment

Revision ID: e65fca53c6e4
Revises: 51def56a9e0a
Create Date: 2023-08-14 14:53:18.963012

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65fca53c6e4'
down_revision = '51def56a9e0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_grading_assignments', sa.Column('assessment_display_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_grading_assignments', 'assessment_display_name')
    # ### end Alembic commands ###
