"""

Delete CourseUsers on Course deletion

Revision ID: 032d8cb686d9
Revises: 0e391512a981
Create Date: 2023-08-16 11:55:26.484701

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032d8cb686d9'
down_revision = '0e391512a981'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_users_course_id_fkey', 'course_users', type_='foreignkey')
    op.create_foreign_key(None, 'course_users', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_users', type_='foreignkey')
    op.create_foreign_key('course_users_course_id_fkey', 'course_users', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
