"""

add preferred_name to user

Revision ID: 33586d9c17bb
Revises: 032d8cb686d9
Create Date: 2023-10-03 11:03:46.177243

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33586d9c17bb'
down_revision = '032d8cb686d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_name')
    # ### end Alembic commands ###
