"""

Add student_display_name and submission_version to CourseGradingAssignmentPair

Revision ID: 51def56a9e0a
Revises: 71eea036bf8e
Create Date: 2023-08-14 14:31:32.459978

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51def56a9e0a'
down_revision = '71eea036bf8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_grading_assignment_pairs', sa.Column('student_display_name', sa.String(), nullable=False))
    op.add_column('course_grading_assignment_pairs', sa.Column('submission_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_grading_assignment_pairs', 'submission_version')
    op.drop_column('course_grading_assignment_pairs', 'student_display_name')
    # ### end Alembic commands ###
