version: "3.3"

services:
  proxy:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
